//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_commerce.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVIS
    {
        public int id_avis { get; set; }
        public string commentaire { get; set; }
        public double note { get; set; }
        public System.DateTime date_avis { get; set; }
        public string id_prod { get; set; }
        public int id_user { get; set; }
    
        public virtual PRODUIT PRODUIT { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
