//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_commerce.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAIL_COMMANDE
    {
        public int id_detail { get; set; }
        public Nullable<int> id_com { get; set; }
        public string id_prod { get; set; }
        public Nullable<int> qte { get; set; }
        public Nullable<int> prix_unitaire { get; set; }
    
        public virtual COMMANDE COMMANDE { get; set; }
        public virtual PRODUIT PRODUIT { get; set; }
    }
}
